# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!DO NOT TOUCH THIS FILE EXCEPT DEVELOPMENT MANAGER!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
FROM nginx:1.27-alpine

COPY conf.d/default.conf /etc/nginx/conf.d/default.conf
COPY html/ /usr/share/nginx/html/

EXPOSE 80
EXPOSE 443
