# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!DO NOT TOUCH THIS FILE EXCEPT DEVELOPMENT MANAGER!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
server {
    listen 80;
    listen [::]:80;
    server_name _;

    location = /health {
        add_header Content-Type text/plain;
        return 200 'ok';
    }

    return 301 https://$host:40943$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name _;

    ssl_certificate /etc/nginx/certs/server.crt;
    ssl_certificate_key /etc/nginx/certs/server.key;

    root /usr/share/nginx/html;
    index login.html;

    location = /dashboard.html {
        return 301 $scheme://$http_host/model.html;
    }

    location ~* \.(?:html|css|js)$ {
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0" always;
        expires -1;
        try_files $uri =404;
    }

    location /api/ {
        proxy_pass http://server_api:8000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        try_files $uri $uri/ /login.html;
    }
}
